server.port: 8888

spring:
  application:
    name: WEATHER_CLIENT_V5
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost   
