FROM openjdk:11
LABEL "Developer"="Rajesh kumar"
LABEL "Microservice"="WeatherMap_API_MS "
WORKDIR /app
COPY ./src/main/resources/application.yml /app/config/
COPY ./src/main/resources/application.properties /app/config/
COPY target/WeatherMapAPIv2-mocroservice-0.0.1-SNAPSHOT.jar WeatherMapAPIv2-mocroservice-0.0.1-SNAPSHOT.jar
EXPOSE 8088
CMD ["java", "-jar", "WeatherMapAPIv2-mocroservice-0.0.1-SNAPSHOT.jar"]